<?php
/**
 * @file
 * Code for the Dewey module
 */

/**
 * Implements hook_menu()
 */

function dewey_menu() {
  $items = array();

  $items['admin/config/system/dewey'] = array(
    'title' => 'Dewey',
    'description' => 'Dewey configuration page.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dewey_config'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/reports/dewey'] = array(
    'title' => 'Dewey report',
    'description' => 'Information about your site for Dewey.',
    'page callback' => 'dewey_report',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function dewey_page_build(&$page) {
  $settings = array(
    'url' => url(drupal_get_path('module', 'dewey').'/php/dewey_counter.php'),
    'data' => array(
      'path' => current_path(),
      'drupal' => DRUPAL_ROOT,
    ),
  );
  $page['content'][] = array(
    '#attached' => array(   
      'js' => array(
        drupal_get_path('module', 'dewey') . '/js/dewey_counter.js' => array(),
      ),
    ),
  );
  $page['content']['#attached']['js'][] = array(
    'data' => array('dewey' => $settings),
    'type' => 'setting',
  );
}

function dewey_config($form, &$form_state) {
  $form['dewey_enabled'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable Dewey to report on this site'),
    '#default_value' => variable_get('dewey_enabled', 1),
    '#description' => t('Enable Dewey to communicate with this site to generate reports for you.'),
  );
  $form['dewey_api_key'] = array(
    '#type' => 'textfield',
    '#title' => t('Dewey API key'),
    '#size' => 30,
    '#maxlength' => 30,
    '#description' => t('The API key of your Dewey account. This will ensure your site links to your Dewey account. <a href="">Get a Dewey API key</a>.'),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

function dewey_report() {
  // Get the timestamp of when the report was taken
  $output['audited'] = time();

  // Get path accesses
  $result = db_query("SELECT path, hits, lastaccess FROM dewey_counter");
  while ($path = $result->fetchAssoc()) {
    $output['traffic'][$path['path']] = array('hits' => $path['hits'], 'last_access' => $path['lastaccess']);
  }

  // Get the file count and file sizes
  $types = array('public', 'private');

  $path['public'] = variable_get('file_public_path', conf_path() . '/files');
  $path['private'] = variable_get('file_private_path');

  foreach($types as $type) {
    $output['files'][$type]['count'] = 0;
    $output['files'][$type]['size'] = 0;

    if (is_dir($path[$type])) {
      $iterator = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($path[$type], RecursiveDirectoryIterator::SKIP_DOTS), RecursiveIteratorIterator::SELF_FIRST);
      $filelist = array();
      foreach($iterator as $file) {
        if (!$file->isDir()) {
          $output['files'][$type]['count']++;
          $output['files'][$type]['size'] += $file->getSize();
        }
      }
    }
  }

  // Get all users, roles and last signons
  $result = db_query("SELECT users.name AS name, mail, access AS last_access, status, role.name AS role FROM users, role, users_roles WHERE users.uid = users_roles.uid AND users_roles.rid = role.rid");
  while ($user = $result->fetchAssoc()) {
    if (isset($output['users'][$user['name']] )) {
      $output['users'][$user['name']]['role'][] = $user['role'];
    } else {
      $output['users'][$user['name']] = $user;
      $output['users'][$user['name']]['role'] = array($user['role']);
    }
  }

  // Get all node content
  $result = db_query("SELECT nid, type, created, changed FROM node");
  while ($node = $result->fetchAssoc()) {
    $output['content']['nodes'][$node['nid']] = array('created' => $node['created'], 'changed' => $node['changed'], 'type' => $node['type']);
  }

  $fields = field_info_fields();
  foreach ($fields as $field) {
    if ($field['module'] == 'text') {
      $table = _field_sql_storage_tablename($field);
      $column = _field_sql_storage_columnname($field['field_name'], 'value');
      $result = db_select($table, 'field')
      ->fields('field', array($column, 'entity_id'))
      ->condition('entity_type', 'node', '=')
      ->execute();
    }
    while ($field = $result->fetchAssoc()) {
      $words = preg_split("/[\s,]+/", strtolower($field[$column]));
      foreach ($words as $word) {
        $output['content']['nodes'][$field['entity_id']]['words'][] = $word;
      }
    }
  }

  // Get all block content
  $result = db_select('block_custom', 'block')
  ->fields('block', array('bid', 'body'))
  ->execute();
  while ($block = $result->fetchAssoc()) {
    $words = preg_split("/[\s,]+/", strtolower($block['body']));
    foreach ($words as $word) {
      $output['content']['blocks'][$block['bid']]['words'][] = $word;
    }
  }

  // Get all enabled modules
  $modules = system_list('module_enabled');
  foreach ($modules as $module => $module_info) {
    $output['modules'][$module_info->info['project']][$module_info->name] = array('schema' => $module_info->schema_version, 'version' => $module_info->info['version']);
  }

  // Get all custom themes
  $themes = list_themes(TRUE);
  foreach ($themes as $theme) {
    if ($theme->info['package'] != 'Core') {
      $output['themes'][$theme->name] = array('version' => $theme->info['version']);
    }
  }

  print json_encode($output);
}