# Schema for the configuration files of the dewy module.

dewy.settings:
  type: config_object
  label: 'Dewy settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enable Dewy to report on this site'
    users:
      type: boolean
      label: 'Include usernames and emails'
    content:
      type: boolean
      label: 'Include content'
    api_key:
      type: string
      label: 'API Key'
    token:
      type: string
      label: 'Token'
